### ISSUE TITLE
'CalcJobNode' object has no attribute 'load_process_class'

### ISSUE THREAD

**Issue by Cloudac7** [aiidateam/aiida-cp2k#19]
When the result of calculation is parsing, it raised the following error:

```
Traceback (most recent call last):
    File "/home/aiida/.local/lib/python3.6/site-packages/plumpy/process_states.py", line 220, in execute
    result = self.run_fn(*self.args, **self.kwargs)
    File "/home/aiida/code/aiida_core/aiida/engine/processes/calcjobs/calcjob.py", line 172, in parse
    exit_code = execmanager.parse_results(self, retrieved_temporary_folder)
    File "/home/aiida/code/aiida_core/aiida/engine/daemon/execmanager.py", line 358, in parse_results
    exit_code = parser.parse(**parse_kwargs)
    File "/home/aiida/code/aiida-cp2k/aiida_cp2k/parsers/__init__.py", line 43, in parse
    self._parse_stdout(out_folder)
    File "/home/aiida/code/aiida-cp2k/aiida_cp2k/parsers/__init__.py", line 56, in _parse_stdout
    fname = self.node.load_process_class()._DEFAULT_OUTPUT_FILE  # pylint: disable=protected-access
AttributeError: 'CalcJobNode' object has no attribute 'load_process_class'
```
In aiida_core v1.0.0b1, the method `load_process_class` exist, while in the latest develop branch the very method has been renamed as `process_class`.

**Comment by yakutovicha** [comment]
Hi @Cloudac7.

We plan to update aiida-cp2k plugin once aiida_core v1.0.0b2 is released. Otherwise we can't properly test the changes on travis.

I will close the issue since keeping the plugin compatible with the latest aiida_core release is anyways our top priority.
