### ISSUE TITLE
UnicodeDecodeError during pip3 installation. 

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida-cp2k#58]
I already mentioned this in #56, but I believe it merits it's own issue.
One can reproduce it via the following Dockerfile:
```
FROM ubuntu:18.04

RUN apt-get update && apt-get install --yes --no-install-recommends \
      python3-setuptools     \
      python3-wheel          \
      python3-pip            \
      git

WORKDIR /opt/
RUN git clone https://github.com/aiidateam/aiida-cp2k.git
RUN pip3 install ./aiida-cp2k/[pre-commit,test]
```

The error message is: 
```
Step 5/5 : RUN pip3 install ./aiida-cp2k/[pre-commit,test]
 ---> Running in f8eb36576ce3
Processing ./aiida-cp2k
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-0im3xx5s-build/setup.py", line 27, in <module>
        run_setup()
      File "/tmp/pip-0im3xx5s-build/setup.py", line 18, in run_setup
        kwargs = json.load(info)
      File "/usr/lib/python3.6/json/__init__.py", line 296, in load
        return loads(fp.read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 160: ordinal not in range(128)
```
I'm also wondering why TravisCI didn't catch this?

**Comment by yakutovicha** [comment]
I think [this](https://stackoverflow.com/a/35052042) might help. Trying it now.

**Comment by yakutovicha** [comment]
Okay, this solves the problem with aiida-cp2k, but there are other dependencies that fail because of the same issue.

Looks like a certain python package needs to be installed/updated.

Investigating this.

**Comment by yakutovicha** [comment]
The problems can also be solved by using `phusion/baseimage:0.11` as the base image.

**Comment by oschuett** [comment]
> This is not a problem of aiida-cp2k plugin, but of the docker file, you used.

I disagree. A pip install should not depend on the locals. Nevertheless, thanks for the workaround.

**Comment by yakutovicha** [comment]
> > This is not a problem of aiida-cp2k plugin, but of the docker file, you used.
> 
> I disagree. A pip install should not depend on the locals. Nevertheless, thanks for the workaround.

How do you then fix the same problem of the dependencies?

**Comment by oschuett** [comment]
Ideally, one should file bugs with each of the broken dependencies. Whether this is worth the trouble ¯\_(ツ)_/¯
